#!/bin/bash
echo -e "This program copies a file to the /stuff directory.\n"
echo -e "Which file would you like to copy? --> \c"
read filename
mkdir /stuff || echo "The /stuff directory could not be created."
cp -f $filename /stuff && echo "$filename was successfully copied to /stuff"
